import { useEffect, useState } from "react";
import { api } from "../services/api.js";
import { inr } from "../utils/money.js";

export default function Reports() {
  const [reports, setReports] = useState({ gst: null, hsn: [], customer: [], monthly: [] });
  useEffect(() => {
    Promise.all([api.reports.gst(), api.reports.hsn(), api.reports.customer(), api.reports.monthly()])
      .then(([gst, hsn, customer, monthly]) => setReports({ gst, hsn, customer, monthly }));
  }, []);
  return <section className="view active">
    <div className="section-head"><div><h1>Reports</h1><p>Reports are generated by PostgreSQL queries.</p></div><a className="secondary small" href={api.backup.excelUrl}>Export Reports</a></div>
    <div className="grid two">
      <div className="panel"><h2>GST Summary</h2><table className="data-table"><tbody>{["taxable_cents", "cgst_cents", "sgst_cents", "igst_cents", "total_gst_cents"].map(k => <tr key={k}><td>{label(k)}</td><td className="num">{inr(reports.gst?.[k])}</td></tr>)}</tbody></table></div>
      <SummaryTable title="HSN/SAC-wise Summary" headers={["HSN/SAC", "Invoices", "Taxable", "GST", "Invoice Value"]} rows={reports.hsn.map(r => [r.hsn, r.invoices, inr(r.taxable_cents), inr(r.gst_cents), inr(r.invoice_value_cents)])} />
      <SummaryTable title="Customer-wise Sales" headers={["Customer", "Invoices", "Taxable", "Invoice Value"]} rows={reports.customer.map(r => [r.client_name, r.invoices, inr(r.taxable_cents), inr(r.invoice_value_cents)])} />
      <SummaryTable title="Monthly Sales Summary" headers={["Month", "Invoices", "Taxable", "Invoice Value"]} rows={reports.monthly.map(r => [r.month, r.invoices, inr(r.taxable_cents), inr(r.invoice_value_cents)])} />
    </div>
  </section>;
}

export function SummaryTable({ title, headers, rows }) {
  return <div className="panel"><h2>{title}</h2><div className="table-wrap"><table className="data-table"><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>)}{!rows.length && <tr><td colSpan={headers.length}>No records.</td></tr>}</tbody></table></div></div>;
}

function label(key) {
  return ({ taxable_cents: "Taxable Value", cgst_cents: "CGST", sgst_cents: "SGST", igst_cents: "IGST", total_gst_cents: "Total GST" })[key];
}
